test/SelfKeyCrowdsale_test.js
Crowdsale start date is now set to a dynamic call to `now()`, and end date is assigned a value of 1 year after start date.
=> [Bug fix] Changed test dates for dynamic assignment

contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_test.js
At the moment of crowdsale finalization, all addresses still pending for KYC verification are closed, meaning refund is made available to such addresses and purchased tokens are burned.
=> [Feature] Automatic KYC clearing (rejection) of all pending addresses on finalization

contracts/SelfKeyCrowdsale.sol, migrations/2_deploy_contracts.js, test/SelfKeyCrowdsale_test.js, test/utils/common.js
Goal was changed from an expected amount of wei to raise to an expected amount of tokens to sell, since we're not tracking the wei contributed amount for pre-sale participants.
=> [Feature, KEY-35] Changed goal to reflect an amount of KEY expected to sell

contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js
ETH/KEY exchange is now manually updatable **until public sale starts**.
=> [Feature, KEY-34] Added  method for updating the ETH/KEY exchange rate

contracts/SelfKeyCrowdsale.sol, migrations/2_deploy_contracts.js, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js, test/SelfKey_test.js, test/utils/common.js
Pre-sale is already closed, therefore the contract will only provide functionality for the public sale (and before start_time, for manually settling all off-chain pre-sale purchases).
Thus, all code functionality regarding public pre-sale was removed.
=> [Feature, KEY-37] Removed all public-presale references and code functionality

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js
New founders' pool token allocation is as follows:
- 1/3 (5.5% of total supply cap) is made immediately available
- 1/3 (5.5% of total supply cap) is time-vested for 6 months
- 1/3 (5.5% of total supply cap) is time-vested for 1 year
=> [Feature, KEY-30] Timelock parameters were updated for founders allocation 

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, migrations/2_deploy_contracts.js, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js, test/SelfKey_test.js, test/utils/common.js, truffle.js
ETH price is updatable via the `setEthPrice` method until sale start date. Conversion rates and USD-defined caps for the public sale are calculated according to this ETH price.
=> [Feature, KEY-32] ETH price is updatable until start date

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, migrations/2_deploy_contracts.js, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js, test/SelfKey_test.js
Gas expenditure during the crowdsale deployment was optimized by removing constructor parameters. All wallet addresses now are hard-coded on the crowdsale config contract.
=> [Feature, KEY-40] Moved crowdsale parameters to config contract for gas optimization

contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_test.js, test/SelfKey_test.js, test/utils/timeTravel.js
_timeTravel_ library by @davesag is used to test founders' timelock releases.
**Warning**: time forwared can't be reverted, so `truffle develop` environment has to be reset for each test run.
=> [Feature, KEY-50] added positive test case for founders' timelock release

contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_test.js
Now it's possible for anyone to trigger a refund for a participant (if refund is enable for such participant or refunds are enabled to anyone due to unsuccessful crowdsale).
=> [Feature, KEY-56] claimRefund is callable by anyone

test/SelfKeyCrowdsale_test.js
Now it considers the case where an already verified address makes a new purchase.
=> [Testing] added test for increasing coverage

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_test.js
Modified `buyTokens` method so that a different max cap per purchaser applies if purchase is made on day 1 of token sale.
=> [Feature, KEY-59] on crowdsale day 1 a different purchaser max cap applies

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js, truffle.js
Added time-locked vesting of tokens for a second founders' address. Legal expenses is now 50% time-vested as well.
=> [Feature, KEY-61] changed splitting for founders and added legal expenses vesting

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_test.js
Legal expenses token allocation is split between two addresses now, with one of them half-vested for 6 months.
=> [Feature, KEY-62] Added splitting for legal expenses allocation

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_test.js
Foundation and community pools were separated as two different addresses for initial distribution, with different allocation percentages according to latest terms.
=> [Feature, KEY-63] Added splitting between foundation and community

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js
Founders' second pool address was substituted by time-vested allocations for the foundation pool.
=> [Feature, KEY-64] initial allocation was changed according to latest terms

contracts/CrowdsaleConfig.sol, contracts/SelfKeyCrowdsale.sol, migrations/2_deploy_contracts.js, test/SelfKeyCrowdsale_presale_test.js, test/SelfKeyCrowdsale_test.js, truffle.js
version 1.1.3 was the final version deployed to the Ethereum network, successfully selling out within 11 minutes during public sale.
=> [Release, 1.1.3] Final release of SelfKey crowdsale and token

contracts/SelfKeyAirdrop.sol, migrations/3_deploy_airdrop.js, test/SelfKeyAirdrop_tests.js, test/SelfKeyCrowdsale_test.js
Added airdrop contract for giving away free tokens to addresses that were verified during the crowdsale.
Airdrop can only be triggered by whitelisted addresses added as "airdroppers". A single address cannot receive the airdrop more than once.
=> [Feature, KEY-77] Airdrop contract

contracts/SelfKeyAirdrop.sol, test/SelfKeyAirdrop_tests.js
An increasing counter was added to keep track of how many airdrops are performed. Additionally, the default airdrop amount was fixed to take into account decimal places (18). Default is set to `10000000000000000000` (10 KEY).
=> [Feature, KEY-84] Added airdrop counter and fixed default airdrop KEY amount

contracts/SelfKeyAirdrop.sol, migrations/3_deploy_airdrop.js, test/SelfKeyAirdrop_tests.js, truffle.js
Any address is now elegible for airdrop since the contract is trusting on the whitelisted airdropper to perform proper interaction with the IDWallet. Airdrop can now be requested from new addresses generated within the SelfKey IDWallet.
=> [Feature, KEY-106] Removed requirement for addresses to be whitelisted for airdrop
